apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: billing-worker-6245
  namespace: MendPerformance
  annotations:
    github.com/project-slug: MendPerformance/billing-worker-6245
spec:
  type: service
  lifecycle: unknown
  owner: mend.io
